In [1]:
import pandas as pd
df=pd.read_excel('dataupdate.xlsx','weather',index_col='Day')
df

            Temperature  WindSpeed    Event
Day
2020-12-01           30          9  แดดร้อน
2020-12-02           28          8   เมฆมาก
2020-12-03           27          4     ฝนตก
2020-12-04           19          3  แดดร้อน
2020-12-05           20          5   เมฆมาก
2020-12-06           25          6     ฝนตก
2020-12-07           36          4     ฝนตก
2020-12-08           28          6     ฝนตก
2020-12-09           17          5   เมฆมาก
2020-12-10           24          6  แดดร้อน
2020-12-11           26          4     ฝนตก
2020-12-12           27          9  แดดร้อน
2020-12-13           30          2  แดดร้อน
2020-12-14           31          5   เมฆมาก
2020-12-15           28          4  แดดร้อน
2020-12-16           27          7  แดดร้อน
2020-12-17           20          8     ฝนตก
2020-12-18           18          5     ฝนตก
2020-12-19           25          7  แดดร้อน
2020-12-20           28          4   เมฆมาก
2020-12-21           25          5   เมฆมาก
2020-12-22           38          2   เมฆมาก
2020-12-23           34          3     ฝนตก
2020-12-24           29          4     ฝนตก
2020-12-25           34          5  แดดร้อน
2020-12-26           25          8     ฝนตก
2020-12-27           28          9   เมฆมาก
2020-12-28           30          2   เมฆมาก
2020-12-29           31          1     ฝนตก
2020-12-30           35          2     ฝนตก

In [3]:
df[df.Temperature<=20]

            Temperature  WindSpeed    Event
Day
2020-12-04           19          3  แดดร้อน
2020-12-05           20          5   เมฆมาก
2020-12-09           17          5   เมฆมาก
2020-12-17           20          8     ฝนตก
2020-12-18           18          5     ฝนตก

In [4]:
df[df.Event=='แดดร้อน']

            Temperature  WindSpeed    Event
Day
2020-12-01           30          9  แดดร้อน
2020-12-04           19          3  แดดร้อน
2020-12-10           24          6  แดดร้อน
2020-12-12           27          9  แดดร้อน
2020-12-13           30          2  แดดร้อน
2020-12-15           28          4  แดดร้อน
2020-12-16           27          7  แดดร้อน
2020-12-19           25          7  แดดร้อน
2020-12-25           34          5  แดดร้อน

In [20]:
df[(df.Event=='ฝนตก') & (df.Temperature >=35)] # & ใช้แทน and

            Temperature  WindSpeed Event
Day
2020-12-07           36          4  ฝนตก
2020-12-30           35          2  ฝนตก

In [19]:
df[(df.Event=='เมฆมาก') | (df.Temperature<=18)]

            Temperature  WindSpeed   Event
Day
2020-12-02           28          8  เมฆมาก
2020-12-05           20          5  เมฆมาก
2020-12-09           17          5  เมฆมาก
2020-12-14           31          5  เมฆมาก
2020-12-18           18          5    ฝนตก
2020-12-20           28          4  เมฆมาก
2020-12-21           25          5  เมฆมาก
2020-12-22           38          2  เมฆมาก
2020-12-27           28          9  เมฆมาก
2020-12-28           30          2  เมฆมาก

In [21]:
df[(df.Temperature==18)|(df.Temperature==30)|(df.Temperature==35)]

            Temperature  WindSpeed    Event
Day
2020-12-01           30          9  แดดร้อน
2020-12-13           30          2  แดดร้อน
2020-12-18           18          5     ฝนตก
2020-12-28           30          2   เมฆมาก
2020-12-30           35          2     ฝนตก

In [26]:
df[(df.Temperature.isin([18,25,30]))] #ใช้ isin แทน or

            Temperature  WindSpeed    Event
Day
2020-12-01           30          9  แดดร้อน
2020-12-06           25          6     ฝนตก
2020-12-13           30          2  แดดร้อน
2020-12-18           18          5     ฝนตก
2020-12-19           25          7  แดดร้อน
2020-12-21           25          5   เมฆมาก
2020-12-26           25          8     ฝนตก
2020-12-28           30          2   เมฆมาก

In [27]:
df[(df.Temperature.isin([35]))]

            Temperature  WindSpeed Event
Day
2020-12-30           35          2  ฝนตก

In [28]:
df[(df.Temperature.isin([20,35]))]

            Temperature  WindSpeed   Event
Day
2020-12-05           20          5  เมฆมาก
2020-12-17           20          8    ฝนตก
2020-12-30           35          2    ฝนตก

In [32]:
df[(df.Temperature.isin([30,35]))&(df.Event=='แดดร้อน')]

            Temperature  WindSpeed    Event
Day
2020-12-01           30          9  แดดร้อน
2020-12-13           30          2  แดดร้อน